{"name": "Логин курьера: несуществующий пользователь", "status": "passed", "description": "Проверка, что авторизация под несуществующим пользователем возвращает ошибку", "steps": [{"name": "Отправка запроса на авторизацию с несуществующими данными", "status": "passed", "start": 1743027261417, "stop": 1743027261781}, {"name": "Проверка кода ответа и сообщения об ошибке", "status": "passed", "start": 1743027261781, "stop": 1743027261781}], "start": 1743027261417, "stop": 1743027261781, "uuid": "bcc7eb6c-8647-4592-8513-891c2b9addf2", "historyId": "84269162486380f5bc31be6a5561465d", "testCaseId": "84269162486380f5bc31be6a5561465d", "fullName": "tests.test_login_courier.TestLoginCounter#test_courier_login_with_nonexistent_credentials_returns_error", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_courier"}, {"name": "subSuite", "value": "TestLoginCounter"}, {"name": "host", "value": "DESKTOP-KCOIQ11"}, {"name": "thread", "value": "2488-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_courier"}]}